### PR TITLE
Implementing progress bar

### LINKED ISSUE #9: Progress bar for download?
Doable?

### PR DESCRIPTION
**Pull request by ProGM**
Fixes #9 

This pull introduces/changes:

 * A progress bar for downloads
 * Removed `httparty` dependency, replaced with `open-uri`

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

**Comment by ProGM** [comment]
It fails also on master, I think 😞 

However, here's a preview!

schermata 2016-05-30 alle 17 26 22

**Comment by cheerfulstoic** [comment]
Hrmmm, I wouldn't be surprised if the failures were just issues with the specs.  They were kind of difficult to get working in the first place.

Exciting about removing the progress bar and the dependency on `httparty` though!

**Comment by ProGM** [comment]
@cheerfulstoic should I fix them? They fail on master as well... Maybe I should open a new PR for it.

> Exciting about removing the progress bar and the dependency on httparty though!

What do you mean for __removing__ the progress bar?

**Comment by cheerfulstoic** [comment]
You're welcome to look into fixing the specs, though you don't have to spend a lot of time on it ;)  Happy to have that as part of the PR.  I'd also be happy to merge the PR if the specs are failing in the same way as on master (though obviously that's not ideal).

And I think I meant to say "**adding** the progress bar" ;)

**Comment by ProGM** [comment]
@cheerfulstoic I fixed the specs! It was easier than I though
However, if it's ok for you, please merge 😉

**Comment by cheerfulstoic** [comment]
Released as 0.6.0!  Thanks!

**Pull request merged**
